// <auto-generated />
using System;
using Fiap.Api.Donation1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231017210035_updatingDB")]
    partial class updatingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugestaoTroca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("TipoProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3874),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3875),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 1",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 2,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3881),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3882),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 2",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 3,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3883),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3883),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 3",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 4,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3884),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3885),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 4",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 5,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3886),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3886),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 5",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 6,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3887),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3888),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 6",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 7,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3889),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3889),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 7",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3890),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3891),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 8",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 9,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3892),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3892),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 9",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 10,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3893),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3894),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 10",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3899),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3899),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 11",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3900),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3900),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 12",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 13,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3902),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3902),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 13",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 14,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3903),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3903),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 14",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 15,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3904),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3905),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 15",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 16,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3906),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3906),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 16",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 17,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3908),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3908),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 17",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 18,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3909),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3909),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 18",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 19,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3910),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3911),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 19",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 20,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3912),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3912),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 20",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 21,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3913),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3914),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 21",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 22,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3915),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3915),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 22",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 23,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3916),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3917),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 23",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 24,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3918),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3918),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 24",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 25,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3919),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3920),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 25",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 26,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3921),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3921),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 26",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 27,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3922),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3923),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 27",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 28,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3924),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3924),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 28",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 29,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3925),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3926),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 29",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 30,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3927),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3927),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 30",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 31,
                            DataCadastro = new DateTime(2023, 10, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3934),
                            DataExpiracao = new DateTime(2025, 4, 17, 18, 0, 34, 466, DateTimeKind.Local).AddTicks(3934),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 31",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.TipoProdutoModel", b =>
                {
                    b.Property<int>("TipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoProdutoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("TipoProdutoId");

                    b.ToTable("TipoProduto");

                    b.HasData(
                        new
                        {
                            TipoProdutoId = 1,
                            Descricao = "Descrição para celular",
                            Nome = "Celular"
                        },
                        new
                        {
                            TipoProdutoId = 2,
                            Descricao = "Descrição para TV",
                            Nome = "TVs"
                        },
                        new
                        {
                            TipoProdutoId = 3,
                            Descricao = "Descrição para ar-condicionado",
                            Nome = "Ar-condicionado"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            EmailUsuario = "rafael@email.com",
                            NomeUsuario = "Super Admin",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 2,
                            EmailUsuario = "carla@email.com",
                            NomeUsuario = "Carla Oliveira",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 3,
                            EmailUsuario = "luciane@email.com",
                            NomeUsuario = "Luciane Oliveira",
                            Regra = "admin",
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation1.Models.TipoProdutoModel", "TipoProduto")
                        .WithMany()
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation1.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProduto");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
